### ISSUE TITLE
Add zip suffix to default export archive name

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/user_migration#169]
The current name of the export archive is `user.nextcloud_export`.

It would be better to have the file suffixed with `zip`. Not only would be a more familiar suffix, also, If I'm not wrong, many files managers give the user the possibility to open a given file with a given program based on the suffix.

**Comment by come-nc** [comment]
The idea of using a custom extension was to be sure that we are not overwriting a user file.
Now it is hard to change the name because it is used to exclude the previous export from the current export, so changing will imply migration complications.

People can rename it to zip if they intend to explore it but the official usecase is to import it though Nextcloud and there is no guarantee about the format.
