### ISSUE TITLE
Do not include shares by default

### ISSUE THREAD

**Issue by svenb1234** [nextcloud/user_migration#203]
I just wanted to migrate a user which has only a few GB of own data, but a lot of shares from another user on the same instance. The user migration included the shares, which does not make sense to me since this would duplicate the data instead of sharing it. AFAIU user migration is not a backup.

Duplicating all shares for export on a big server would mean you would need an insane amount of space available.

Expected behaviour would be that shares are excluded by default - and if that makes sense, can be included when selecting the data types before starting the export. Currently there is not even a way to de-select shares, one has to leave them one by one before starting the data migration.

**Comment by Pytal** [comment]
This behaviour allows for a user to have access to the same data before and after importing and migration of shared files is being tracked in https://github.com/nextcloud/user_migration/issues/144

@come-nc what do you think about making this an option?

**Comment by svenb1234** [comment]
I think the idea is not wrong per se. But as you wrote as well, it should allow not force the user  to do so. 

Imagine migrating multiple users who share common shares, e.g. the family's photos. Even on home servers this amounts to hundreds of GB which get duplicated. That is against the original idea of sharing instead of copying.

**Comment by come-nc** [comment]
@Pytal I think it is true that current behavior is unusable when there is a lot of data, which happens more often when including shares.

It would make sense to split files and shared files in the migrators I suppose.

What bugs me is that this will not fix all problems, there might still be way too much data even with local files only. So in the end a selection of which paths to export and to ignore might be needed.

As that seems too complex for now I would go with splitting files export into files, shares, and external files. I suppose implementation wise the easiest is to do separated migrators for those, so that they appear in the UI?

But the idea with shares was to export them to federated shares in the roadmap. So maybe we should just remove them from export for now?

**Comment by come-nc** [comment]
My recommendation is to just ignore shares and external files in FilesMigrator export, people can always migrate files by hand if they need the content. And later add a ShareMigrator to migrate shares to federated shares.
