### ISSUE TITLE
Export is frozen on "Export queued" 

### ISSUE THREAD

**Issue by Majed610** [nextcloud/user_migration#393]
Hi, 

i have started more than 36 hours ago an User export of just User and personal preferences with a total size of 2 MiB. It is still just showing that it preparing the Data for export and its almost two days now. 

I have tried more than one user and it is always the same problem. 

Any suggestion what might be wrong. 

NC Version 25.0.5
Server is Ubuntu

**Comment by Pytal** [comment]
Thanks for the report @Majed610

Please try getting the background job id (number on the left) with:
```
occ background-job:list -l 1000 | grep UserExportJob
```

Then executing it:
```
occ background-job:execute <id>
```

**Comment by Majed610** [comment]
Hi @Pytal, 

thanks for the quick reply. 

I tried the obove mention code but it comes back with an error 
![image](https://user-images.githubusercontent.com/89200332/231845364-cfb0ba90-3c4e-4a6a-9e60-3623a9302c36.png)

And i tried the _occ background-job:list -l_  and there is no Userexport Job
![image](https://user-images.githubusercontent.com/89200332/231845586-33cac8d6-f4ac-4c5a-b9a5-858ddf665ea8.png)

Any suggestions? 

Thanks in advance

**Comment by Pytal** [comment]
Was an export queued? The job will only be listed when it is queued

Try the commands while an export is queued and let us know your results

**Comment by Majed610** [comment]
HI @Pytal, 

the export was queued when i took the above screenshots.

**Comment by Pytal** [comment]
Ahh then I think you missed the `-l 1000` part of `background-job:list` as the default limit is 10

**Comment by Majed610** [comment]
Even then the Job is not listed. Instead i got a huge number of weird jobs running in the background: 
![image](https://user-images.githubusercontent.com/89200332/231967389-8148f54a-2931-4a92-9a2a-d9383272c0cb.png)


Some of the jobs mention deleted users. And i have no clue where to stop them.

**Comment by thwint** [comment]
I just face the same issue. Starting an export job seems to queue it but there is no job UserExportJob visible using occ.
I can't tell it ever worked  because I just installed the app and tried to use it for the first time.

The problem inn my case exists on all the following versions of Nextcloud: 24, 25 and 26

On NC 24 I tried using version 1.1.0 on the others with 3.0.0

Finally it turned out that cron was not set up correctly

**Comment by Pytal** [comment]
> Finally it turned out that cron was not set up correctly

Is this the case for you @Majed610?

**Comment by Majed610** [comment]
I will try to check with a collegue who originally setup the nextcloud and the cron jobs and try to chec the cron configuration.

**Comment by Niveshkrishna** [comment]
@Majed610 I also face the same issue. The job is queued for several days and I don't see a entry for it in bg-job:list

**Comment by Niveshkrishna** [comment]
@Pytal I too agree that it a cron issue. Thanks @thwint for the hint

**Comment by mtk089** [comment]
This was a major issue for me.  I beat my head against my keyboard for a few days.  It turned out that Cron was not set up properly.  I just followed the instructions at [https://docs.nextcloud.com/server/19/admin_manual/configuration_server/background_jobs_configuration.html](url)

I really wish Nextcloud would add this to the initial setup documentation in the future.  I would have saved me a ton of cgreif

**Comment by Pytal** [comment]
Closed by https://github.com/nextcloud/documentation/pull/11032
