### ISSUE TITLE
Do not create new section for data migration in settings

### ISSUE THREAD

**Issue by Niveshkrishna** [nextcloud/user_migration#401]
If there's a section already defined with data migration do not add a new section with same name. For example, when we have google integration app enabled in nextcloud, it creates an item to section with name `Data migration` and now when we enable this app, we have two `Data migration` sections in settings. 

Please merge them and create a single data migration section in settings as this will avoid confusion.

![image](https://user-images.githubusercontent.com/16881005/234960187-dbc8e5ad-3f48-4412-9fde-81ccfc0047f6.png)

**Comment by Niveshkrishna** [comment]
We basically have to change this line 

https://github.com/nextcloud/user_migration/blob/e4e5a339e7abca1e952266cc1f3fa96b5c6edb3d/lib/Settings/Personal/Settings.php#L70


to 

`return 'migration'`

**Comment by Pytal** [comment]
🤔 that would group `user_migration` with the unrelated cloud integration `integration_*` apps ([query](https://github.com/search?type=code&q=org%3Anextcloud+%22return+%27migration%27%22))

Best option would probably be to use different names for the sections

How should we name these sections distinctly @jancborchardt?

**Comment by Niveshkrishna** [comment]
@Pytal integration_* apps basically imports data from other cloud services into nextcloud, and this app allow import and export functionality within nextcloud. IMO both of them can be clubbed into same section.

**Comment by jancborchardt** [comment]
>  integration_* apps basically imports data from other cloud services into nextcloud, and this app allow import and export functionality within nextcloud. IMO both of them can be clubbed into same section.

Yeah, from a user perspective import/export, whether it is internal or external can be treated the same. :) @Pytal we can group it in the same section.

**Comment by jancborchardt** [comment]
And the icon can be the "person" one, the lowest entry in this screenshot by @Niveshkrishna: https://github.com/nextcloud/user_migration/issues/401#issue-1687374900

**Comment by Pytal** [comment]
How should we order the settings themselves @jancborchardt? Should it be `user_migration` settings first then `integration_*` or the other way around?

**Comment by JimmyKater** [comment]
isn't it completely irrelevant how it's sorted? 
I mean just do it... it seems to be a single and easy change to make. And though it tooks almost a year to implement it because you wait for someone to answer on it taking into account that up to now there are two sections with the same name?

What do you think is worse: two sections by the same name confusing the user or maybe a wrong sorting within one section (which could be solved in a 2nd step if neccessary)?

I'd go with the first one.

Other than that @Pytal thanks for replying (and closing) to my other issue. I didn't find this one here while searching for it.

**Comment by jancborchardt** [comment]
@Pytal if it’s still relevant: First integration, then migration, then deletion. :)
